version: "3.7"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "***REMOVED FOR SECURITY REASONS***"
      MYSQL_USERNAME: "***REMOVED FOR SECURITY REASONS***"
      MYSQL_PASSWORD: "***REMOVED FOR SECURITY REASONS***"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3307:3306"

  memcache:
    image: "artifacts.intranet.mckinsey.com/gold-images/memcached:1.5"

  carom:
    depends_on:
      - "db"
      - "memcache"
    build: .
    ports:
      - "3006:3000"
    environment:
      CAROM_DATABASE_USERNAME: root
      CAROM_DATABASE_PASSWORD: root
      CAROM_DATABASE_NAME: "***REMOVED FOR SECURITY REASONS***"
      CAROM_DATABASE_PORT: 3306
      CAROM_DATABASE_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      CACHE_HOST: memcache
    volumes:
      - ".:/app"

volumes:
  db: