name: 02. Deploy on on-prem K8s integration
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy (ignore to use the latest git commit sha)'

  # Trigger from other workflow
  workflow_call:
    inputs:
      workflowsha:
        required: true
        type: string
      triggertype:
        required: true
        type: string
    secrets:
      ROLE_ID:
        required: true
      SECRET_ID:
        required: true

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: integration-deploy-${{ github.ref }}

jobs:
  deploy_on_k8s_integration:
    runs-on: [ linux, on-prem ]
    environment: integration_with_proposetowin_namespace
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Generate shortsha
        id: shortsha
        run: echo "shortsha=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Evaluate image tag to deploy
        id: imagetag_to_deploy
        run: echo "imagetag_to_deploy=${{inputs.workflowsha || github.event.inputs.tag || steps.shortsha.outputs.shortsha}}" >> $GITHUB_OUTPUT

      - name: Calling k8s-deployer:latest make helm-deploy
        env:
          NAMESPACE: k8sdevsf01-proposetowin-devsf
          ENV: devsf01
          SERVICENAME: carom
          IMAGE_VERSION: ${{steps.imagetag_to_deploy.outputs.imagetag_to_deploy}}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
        run: |
          docker run -i --rm -v `pwd`/deployment:/workdir/app -e ENV -e NAMESPACE -e SERVICENAME -e ROLE_ID -e SECRET_ID -e IMAGE_VERSION artifacts.intranet.mckinsey.com/deployer-tools/k8s-deployer:latest make helm-deploy
