name: 02. Deploy on on-prem K8s integration
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy (ignore to use the latest git commit sha)'

  # Dependency to a forking workflow
  workflow_run:
    workflows: [ "01. Checkout, Build And Push to jFrog on-prem and jFrog on-cloud" ]
    types:
      - completed

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: integration-deploy-${{ github.ref }}

jobs:
  deploy_on_k8s_integration:
    runs-on: [ linux, on-prem ]
    environment: integration_with_proposetowin_namespace
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Generate shortsha
        id: shortsha
        run: echo "::set-output name=shortsha::sha-$(git rev-parse --short HEAD)"

      - name: Calling k8s-deployer:latest make helm-deploy
        env:
          NAMESPACE: k8sdevsf01-proposetowin-devsf
          ENV: devsf01
          SERVICENAME: carom
          IMAGE_VERSION: ${{github.event.inputs.tag || steps.shortsha.outputs.shortsha}}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
        run: |
          docker run -i --rm -v `pwd`/deployment:/workdir/app -e ENV -e NAMESPACE -e SERVICENAME -e ROLE_ID -e SECRET_ID -e IMAGE_VERSION artifacts.intranet.mckinsey.com/deployer-tools/k8s-deployer:latest make helm-deploy